# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbc3302d7e80401741c0dd94a145b7602f2fc13019f4f32149776ddaff40ac4b7061e45412c5bc55959df3edcc21c7f190eedaeda2a63e2344fdae6610efac00

test:
  secret_key_base: b1f04e73cb4fc1356f488f152957669d3a7a0c2bddace2db577c9854cbc526b36245bf53216f46baabb9a8941a4dc89018b0f220a3ecf59b21712988e9cbfbb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
